### ISSUE TITLE
6.x link die

### ISSUE THREAD

**Issue by nguyenbaodanh** [rogeraabbccdd/CSGO_WP_Private#2]
Any 6.x leaked version link else where to find?
Thanks

**Comment by Bara** [comment]
https://github.com/kaganus/Franug-Weapon_Paints/tree/master/scripting
or...
[franuq.zip](https://github.com/rogeraabbccdd/CSGO_Weapon_Paints_Private/files/1484298/franuq.zip)

**Comment by Bara** [comment]
[nogsltban.zip](https://github.com/rogeraabbccdd/CSGO_Weapon_Paints_Private/files/1484299/nogsltban.zip)
if you want the nogsltban extension (mm plugin)

**Comment by nguyenbaodanh** [comment]
Thanks so much Bara <3

**Comment by rogeraabbccdd** [comment]
New version leaked
https://github.com/WardPearce/Franc1sco-Franug-Leaked-Plugins
